class Piece:
    def __init__(self, color):
        self.__color__ = color

class Rook(Piece): 
    ...
class Pawn(Piece):
    ...
class Knight(Piece):
    ...
class Bishop(Piece):
    ...
class Queen(Piece):
    ...
class King(Piece):
    ... 